### ISSUE TITLE
Image building fail during executing make prebuild command.

### ISSUE THREAD

**Issue by thsmfe001** [mlcommons/inference_results_v3.1#21]
I tried to execute make prebuild command on /closed/NVIDIA directory.
How to solve this problem?

775.6 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager.                                                                                                    It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
780.0 Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
780.1 Collecting apex@ git+https://github.com/nvidia/apex@0da3ffb92ee6fbe5336602f0e3989db1cd16f880 (from -r requirements.x86_64.2.txt (lin                                                                                                   e 1))
780.1   Cloning https://github.com/nvidia/apex (to revision 0da3ffb92ee6fbe5336602f0e3989db1cd16f880) to ./pip-install-177uc4fo/apex_06721                                                                                                   f2a06e34e55be55df8d71638642
780.1   Running command git clone --filter=blob:none --quiet https://github.com/nvidia/apex /tmp/pip-install-177uc4fo/apex_06721f2a06e34e5                                                                                                   5be55df8d71638642
781.6   Running command git rev-parse -q --verify 'sha^0da3ffb92ee6fbe5336602f0e3989db1cd16f880'
781.6   Running command git fetch -q https://github.com/nvidia/apex 0da3ffb92ee6fbe5336602f0e3989db1cd16f880
782.1   Running command git checkout -q 0da3ffb92ee6fbe5336602f0e3989db1cd16f880
783.2   Resolved https://github.com/nvidia/apex to commit 0da3ffb92ee6fbe5336602f0e3989db1cd16f880
783.2   Running command git submodule update --init --recursive -q
793.7   Preparing metadata (setup.py): started
795.3   Preparing metadata (setup.py): finished with status 'error'
795.3   error: subprocess-exited-with-error
795.3
795.3   × python setup.py egg_info did not run successfully.
795.3   │ exit code: 1
795.3   ╰─> [8 lines of output]
795.3       Traceback (most recent call last):
795.3         File "<string>", line 2, in <module>
795.3         File "<pip-setuptools-caller>", line 34, in <module>
795.3         File "/tmp/pip-install-177uc4fo/apex_06721f2a06e34e55be55df8d71638642/setup.py", line 10, in <module>
795.3           from torch.utils.cpp_extension import BuildExtension, CppExtension, CUDAExtension, CUDA_HOME, load
795.3         File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 25, in <module>
795.3           from pkg_resources import packaging  # type: ignore[attr-defined]
795.3       ImportError: cannot import name 'packaging' from 'pkg_resources' (/usr/local/lib/python3.8/dist-packages/pkg_resources/__init_                                                                                                   _.py)
795.3       [end of output]
795.3
795.3   note: This error originates from a subprocess, and is likely not a problem with pip.
795.3 error: metadata-generation-failed
795.3
795.3 × Encountered error while generating package metadata.
795.3 ╰─> See above for output.
795.3
795.3 note: This is an issue with the package mentioned above, not pip.
795.3 hint: See above for details.
------
Dockerfile.x86_64:129
--------------------
 128 |     # Break requirements into two lists because some of them require that other packages be fully installed first.
 129 | >>> RUN python3 -m pip install -r requirements.x86_64.1.txt \
 130 | >>>  && python3 -m pip install -r requirements.x86_64.2.txt
 131 |
--------------------
ERROR: failed to solve: process "/bin/bash -c python3 -m pip install -r requirements.x86_64.1.txt  && python3 -m pip install -r requiremen                                                                                                   ts.x86_64.2.txt" did not complete successfully: exit code: 1
make[1]: *** [Makefile.docker:259: build_docker] Error 1
make[1]: Leaving directory '/mnt/sdb/mlperf/code/inference_results_v3.1/closed/NVIDIA'
make: *** [/mnt/sdb/mlperf/code/inference_results_v3.1/closed/NVIDIA/Makefile.docker:247: prebuild] Error 2

**Comment by dimen2000** [comment]
Hello, adding `setuptools==69.5.1` to [ closed/NVIDIA/docker/requirements.x86_64.1.txt](https://github.com/mlcommons/inference_results_v3.1/blob/main/closed/NVIDIA/docker/requirements.x86_64.1.txt) worked for me
